apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: plugins.dashboard.k8s.io
spec:
  group: dashboard.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: plugins
    singular: plugin
    kind: Plugin
    shortNames:
      - pl
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            configMapRef:
              type: string
          required:
            - configMapRef